services:
  frontend:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    user: vscode
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "4321:4321"
    env_file:
      - .env
    networks:
      - rg-det-shared

networks:
  rg-det-shared:
    name: rg-det-shared
    driver: bridge
