// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};

/**
 * ERROR_400
 *
 * Bad request, input malformed.
 */
export type Def0 = {
    status: string;
    message: string;
    payload?: unknown;
    internal?: {
        stack?: string;
        cause?: string;
    };
};

/**
 * ERROR_401
 *
 * Unauthorized
 */
export type Def1 = {
    status: string;
    message: string;
    payload?: unknown;
    internal?: {
        stack?: string;
        cause?: string;
    };
};

/**
 * ERROR_403
 *
 * Forbidden
 */
export type Def2 = {
    status: string;
    message: string;
    payload?: unknown;
    internal?: {
        stack?: string;
        cause?: string;
    };
};

/**
 * ERROR_405
 *
 * Method not allowed
 */
export type Def3 = {
    status: string;
    message: string;
    payload?: unknown;
    internal?: {
        stack?: string;
        cause?: string;
    };
};

/**
 * ERROR_500
 *
 * Internal server error
 */
export type Def4 = {
    status: string;
    message: string;
    payload?: unknown;
    internal?: {
        stack?: string;
        cause?: string;
    };
};

export type GetAppDownloadLinkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/appDownload/link';
};

export type GetAppDownloadLinkErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetAppDownloadLinkError = GetAppDownloadLinkErrors[keyof GetAppDownloadLinkErrors];

export type GetAppDownloadLinkResponses = {
    /**
     * Default Response
     */
    200: string;
};

export type GetAppDownloadLinkResponse = GetAppDownloadLinkResponses[keyof GetAppDownloadLinkResponses];

export type DeleteBaseLayerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/baseLayer/{id}';
};

export type DeleteBaseLayerByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type DeleteBaseLayerByIdError = DeleteBaseLayerByIdErrors[keyof DeleteBaseLayerByIdErrors];

export type DeleteBaseLayerByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PatchBaseLayerData = {
    body: {
        href: string | unknown;
        visibleForGroups: Array<string>;
        id: string;
        isPublic: boolean;
    };
    path?: never;
    query?: never;
    url: '/baseLayer';
};

export type PatchBaseLayerErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PatchBaseLayerError = PatchBaseLayerErrors[keyof PatchBaseLayerErrors];

export type PatchBaseLayerResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PutBaseLayerData = {
    body: {
        href: string;
        name: string;
        type: 'TILES3D' | 'TERRAIN' | 'IMAGERY' | 'WMS';
    };
    path?: never;
    query?: never;
    url: '/baseLayer';
};

export type PutBaseLayerErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PutBaseLayerError = PutBaseLayerErrors[keyof PutBaseLayerErrors];

export type PutBaseLayerResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PostBaseLayerListChangesData = {
    body: {
        /**
         * This is a unix timestamp, which is defined as the midnight at the beginning of January 1, 1970, UTC.
         */
        timestamp: number;
    };
    path?: never;
    query?: never;
    url: '/baseLayer/listChanges';
};

export type PostBaseLayerListChangesErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostBaseLayerListChangesError = PostBaseLayerListChangesErrors[keyof PostBaseLayerListChangesErrors];

export type PostBaseLayerListChangesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        href: string;
        type: string;
        description: string;
    }>;
};

export type PostBaseLayerListChangesResponse = PostBaseLayerListChangesResponses[keyof PostBaseLayerListChangesResponses];

export type GetBaseLayerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/baseLayer/list';
};

export type GetBaseLayerListErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetBaseLayerListError = GetBaseLayerListErrors[keyof GetBaseLayerListErrors];

export type GetBaseLayerListResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        href: string;
        type: string;
        description: string;
    }>;
};

export type GetBaseLayerListResponse = GetBaseLayerListResponses[keyof GetBaseLayerListResponses];

export type PostConverter3dConvertProjectModelData = {
    body: {
        epsgCode: string;
        fileName: string;
        token: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/convertProjectModel';
};

export type PostConverter3dConvertProjectModelErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dConvertProjectModelError = PostConverter3dConvertProjectModelErrors[keyof PostConverter3dConvertProjectModelErrors];

export type PostConverter3dConvertProjectModelResponses = {
    /**
     * Default Response
     */
    200: {
        jobId: string;
        secret: string;
    };
};

export type PostConverter3dConvertProjectModelResponse = PostConverter3dConvertProjectModelResponses[keyof PostConverter3dConvertProjectModelResponses];

export type PostConverter3dGetProjectModelStatusData = {
    body: {
        jobId: string;
        secret: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/getProjectModelStatus';
};

export type PostConverter3dGetProjectModelStatusErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dGetProjectModelStatusError = PostConverter3dGetProjectModelStatusErrors[keyof PostConverter3dGetProjectModelStatusErrors];

export type PostConverter3dGetProjectModelStatusResponses = {
    /**
     * Default Response
     */
    200: {
        state: 'active' | 'delayed' | 'prioritized' | 'waiting' | 'completed' | 'waiting-children' | 'unknown';
        progress: number;
        modelMatrix?: Array<number>;
    };
};

export type PostConverter3dGetProjectModelStatusResponse = PostConverter3dGetProjectModelStatusResponses[keyof PostConverter3dGetProjectModelStatusResponses];

export type PostConverter3dDownloadProjectModelData = {
    body: {
        jobId: string;
        projectId: string;
        secret: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/downloadProjectModel';
};

export type PostConverter3dDownloadProjectModelErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dDownloadProjectModelError = PostConverter3dDownloadProjectModelErrors[keyof PostConverter3dDownloadProjectModelErrors];

export type PostConverter3dDownloadProjectModelResponses = {
    /**
     * Default Response
     */
    200: {
        href: string;
    };
};

export type PostConverter3dDownloadProjectModelResponse = PostConverter3dDownloadProjectModelResponses[keyof PostConverter3dDownloadProjectModelResponses];

export type PostConverter3dConvertTerrainData = {
    body: {
        srcSRS: string;
        name: string;
        token: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/convertTerrain';
};

export type PostConverter3dConvertTerrainErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dConvertTerrainError = PostConverter3dConvertTerrainErrors[keyof PostConverter3dConvertTerrainErrors];

export type PostConverter3dConvertTerrainResponses = {
    /**
     * Default Response
     */
    200: {
        jobId: string;
    };
};

export type PostConverter3dConvertTerrainResponse = PostConverter3dConvertTerrainResponses[keyof PostConverter3dConvertTerrainResponses];

export type PostConverter3dConvert3dTileData = {
    body: {
        srcSRS: string;
        appearance: string;
        name: string;
        token: string;
        hasAlphaEnabled: boolean;
    };
    path?: never;
    query?: never;
    url: '/converter3D/convert3DTile';
};

export type PostConverter3dConvert3dTileErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dConvert3dTileError = PostConverter3dConvert3dTileErrors[keyof PostConverter3dConvert3dTileErrors];

export type PostConverter3dConvert3dTileResponses = {
    /**
     * Default Response
     */
    200: {
        jobId: string;
    };
};

export type PostConverter3dConvert3dTileResponse = PostConverter3dConvert3dTileResponses[keyof PostConverter3dConvert3dTileResponses];

export type PostConverter3dCommitUploadData = {
    body: {
        token: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/commitUpload';
};

export type PostConverter3dCommitUploadErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dCommitUploadError = PostConverter3dCommitUploadErrors[keyof PostConverter3dCommitUploadErrors];

export type PostConverter3dCommitUploadResponses = {
    /**
     * Default Response
     */
    200: boolean;
};

export type PostConverter3dCommitUploadResponse = PostConverter3dCommitUploadResponses[keyof PostConverter3dCommitUploadResponses];

export type PostConverter3dUploadBlockData = {
    body: {
        block: Blob | File;
        total: string;
        index: string;
        token: string;
    };
    path?: never;
    query?: never;
    url: '/converter3D/uploadBlock';
};

export type PostConverter3dUploadBlockErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dUploadBlockError = PostConverter3dUploadBlockErrors[keyof PostConverter3dUploadBlockErrors];

export type PostConverter3dUploadBlockResponses = {
    /**
     * Default Response
     */
    200: boolean;
};

export type PostConverter3dUploadBlockResponse = PostConverter3dUploadBlockResponses[keyof PostConverter3dUploadBlockResponses];

export type PostConverter3dConvertWmswmtsData = {
    body: {
        name: string;
        url: string;
        layer: string;
        startZoom: number;
        endZoom: number;
    };
    path?: never;
    query?: never;
    url: '/converter3D/convertWMSWMTS';
};

export type PostConverter3dConvertWmswmtsErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostConverter3dConvertWmswmtsError = PostConverter3dConvertWmswmtsErrors[keyof PostConverter3dConvertWmswmtsErrors];

export type PostConverter3dConvertWmswmtsResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetConverter3dGetUploadTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/converter3D/getUploadToken';
};

export type GetConverter3dGetUploadTokenErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetConverter3dGetUploadTokenError = GetConverter3dGetUploadTokenErrors[keyof GetConverter3dGetUploadTokenErrors];

export type GetConverter3dGetUploadTokenResponses = {
    /**
     * Default Response
     */
    200: string;
};

export type GetConverter3dGetUploadTokenResponse = GetConverter3dGetUploadTokenResponses[keyof GetConverter3dGetUploadTokenResponses];

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events';
};

export type GetEventsErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors];

export type GetEventsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        /**
         * Event id.
         */
        id: string;
        /**
         * Can be one of MISSING_HOST, ACTIVE, PLANNED, CANCELED, END.
         */
        status: string;
        endTime: string;
        startTime: string;
        projectId: string | unknown;
        title: string;
        owner: {
            name: string | unknown;
            email: string;
            id: string;
        };
        moderators: Array<{
            name: string | unknown;
            email: string;
            id: string;
        }>;
    }>;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type PutEventsData = {
    body: {
        endTime: string;
        startTime: string;
        title: string;
        attendees: Array<string>;
        moderators: Array<string>;
        project?: string;
    };
    path?: never;
    query?: never;
    url: '/events';
};

export type PutEventsErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PutEventsError = PutEventsErrors[keyof PutEventsErrors];

export type PutEventsResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type DeleteEventsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}';
};

export type DeleteEventsByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type DeleteEventsByIdError = DeleteEventsByIdErrors[keyof DeleteEventsByIdErrors];

export type DeleteEventsByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PatchEventsByIdData = {
    body: {
        id: string;
        endTime?: string;
        startTime?: string;
        status?: string;
        title?: string;
        attendees?: Array<string>;
        moderators: Array<string>;
        project?: string | unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}';
};

export type PatchEventsByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PatchEventsByIdError = PatchEventsByIdErrors[keyof PatchEventsByIdErrors];

export type PatchEventsByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetEventsByIdStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/status';
};

export type GetEventsByIdStatusErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetEventsByIdStatusError = GetEventsByIdStatusErrors[keyof GetEventsByIdStatusErrors];

export type GetEventsByIdStatusResponses = {
    /**
     * Server-Sent Events stream. Each message is UTF-8 text containing lines like "data: <JSON>".
     */
    200: string;
};

export type GetEventsByIdStatusResponse = GetEventsByIdStatusResponses[keyof GetEventsByIdStatusResponses];

export type PostEventsByIdHeartbeatData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/heartbeat';
};

export type PostEventsByIdHeartbeatErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostEventsByIdHeartbeatError = PostEventsByIdHeartbeatErrors[keyof PostEventsByIdHeartbeatErrors];

export type PostEventsByIdHeartbeatResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PostEventsByIdHostData = {
    body: {
        joinCode: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/host';
};

export type PostEventsByIdHostErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostEventsByIdHostError = PostEventsByIdHostErrors[keyof PostEventsByIdHostErrors];

export type PostEventsByIdHostResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PostEventsByIdEndData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/end';
};

export type PostEventsByIdEndErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostEventsByIdEndError = PostEventsByIdEndErrors[keyof PostEventsByIdEndErrors];

export type PostEventsByIdEndResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PostEventsByIdRehostData = {
    body: {
        joinCode: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/rehost';
};

export type PostEventsByIdRehostErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostEventsByIdRehostError = PostEventsByIdRehostErrors[keyof PostEventsByIdRehostErrors];

export type PostEventsByIdRehostResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type DeleteProjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type DeleteProjectByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type DeleteProjectByIdError = DeleteProjectByIdErrors[keyof DeleteProjectByIdErrors];

export type DeleteProjectByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetProjectByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type GetProjectByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetProjectByIdError = GetProjectByIdErrors[keyof GetProjectByIdErrors];

export type GetProjectByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        description: string;
        sasQueryParameters: string;
        img: string | unknown;
        title: string;
        isReadOnly: boolean;
        camera: string | unknown;
        visualAxes: Array<{
            id: string;
            name: string;
            description: string;
            startPoint: {
                x: number;
                y: number;
                z: number;
            };
            endPoint: {
                x: number;
                y: number;
                z: number;
            };
        }>;
        startingPoints: Array<{
            id: string;
            name: string;
            description: string;
            /**
             * Base64 encoded data url (https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data)
             */
            img: string;
            startPoint: {
                x: number;
                y: number;
                z: number;
            };
            uiStartPoint: {
                x: string;
                y: string;
                z: string;
            };
            uiStartPointEpsg: string;
            endPoint: {
                x: number;
                y: number;
                z: number;
            };
            uiEndPoint: {
                x: string;
                y: string;
                z: string;
            };
            uiEndPointEpsg: string;
        }>;
        layers: Array<{
            name: string;
            id: string;
            includedBaseLayers: Array<string>;
            includedExtensionLayers: Array<string>;
            clippingPolygons: Array<{
                name: string;
                id: string;
                points: Array<{
                    x: number;
                    y: number;
                    z: number;
                }>;
                affectsTerrain: boolean;
            }>;
            projectModels: Array<{
                id: string;
                name: string;
                href: string;
                attributes: {
                    [key: string]: string;
                };
                rotation: {
                    x: number;
                    y: number;
                    z: number;
                    w: number;
                };
                uiRotation: {
                    x: string;
                    y: string;
                    z: string;
                };
                scale: {
                    x: number;
                    y: number;
                    z: number;
                };
                uiScale: {
                    x: string;
                    y: string;
                    z: string;
                };
                translation: {
                    x: number;
                    y: number;
                    z: number;
                };
                uiTranslation: {
                    x: string;
                    y: string;
                    z: string;
                };
                uiEpsg: string;
            }>;
        }>;
        extensionLayers: Array<{
            id: string;
            name: string;
            href: string;
            type: string;
        }>;
        allAvailableBaseLayers: Array<{
            id: string;
            name: string;
            description: string;
            sizeGB: number;
            href: string;
            type: string;
        }>;
    };
};

export type GetProjectByIdResponse = GetProjectByIdResponses[keyof GetProjectByIdResponses];

export type PostProjectByIdData = {
    body: {
        id: string;
        description: string;
        sasQueryParameters: string;
        img: string | unknown;
        title: string;
        isReadOnly: boolean;
        camera: string | unknown;
        visualAxes: Array<{
            id: string;
            name: string;
            description: string;
            startPoint: {
                x: number;
                y: number;
                z: number;
            };
            endPoint: {
                x: number;
                y: number;
                z: number;
            };
        }>;
        startingPoints: Array<{
            id: string;
            name: string;
            description: string;
            /**
             * Base64 encoded data url (https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data)
             */
            img: string;
            startPoint: {
                x: number;
                y: number;
                z: number;
            };
            uiStartPoint: {
                x: string;
                y: string;
                z: string;
            };
            uiStartPointEpsg: string;
            endPoint: {
                x: number;
                y: number;
                z: number;
            };
            uiEndPoint: {
                x: string;
                y: string;
                z: string;
            };
            uiEndPointEpsg: string;
        }>;
        layers: Array<{
            name: string;
            id: string;
            includedBaseLayers: Array<string>;
            includedExtensionLayers: Array<string>;
            clippingPolygons: Array<{
                name: string;
                id: string;
                points: Array<{
                    x: number;
                    y: number;
                    z: number;
                }>;
                affectsTerrain: boolean;
            }>;
            projectModels: Array<{
                id: string;
                name: string;
                href: string;
                attributes: {
                    [key: string]: string;
                };
                rotation: {
                    x: number;
                    y: number;
                    z: number;
                    w: number;
                };
                uiRotation: {
                    x: string;
                    y: string;
                    z: string;
                };
                scale: {
                    x: number;
                    y: number;
                    z: number;
                };
                uiScale: {
                    x: string;
                    y: string;
                    z: string;
                };
                translation: {
                    x: number;
                    y: number;
                    z: number;
                };
                uiTranslation: {
                    x: string;
                    y: string;
                    z: string;
                };
                uiEpsg: string;
            }>;
        }>;
        extensionLayers: Array<{
            id: string;
            name: string;
            href: string;
            type: string;
        }>;
        allAvailableBaseLayers: Array<{
            id: string;
            name: string;
            description: string;
            sizeGB: number;
            href: string;
            type: string;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}';
};

export type PostProjectByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type PostProjectByIdError = PostProjectByIdErrors[keyof PostProjectByIdErrors];

export type PostProjectByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetProjectListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/project/list';
};

export type GetProjectListErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetProjectListError = GetProjectListErrors[keyof GetProjectListErrors];

export type GetProjectListResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        description: string;
    }>;
};

export type GetProjectListResponse = GetProjectListResponses[keyof GetProjectListResponses];

export type GetProjectListSharedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/project/listShared';
};

export type GetProjectListSharedErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetProjectListSharedError = GetProjectListSharedErrors[keyof GetProjectListSharedErrors];

export type GetProjectListSharedResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        description: string;
    }>;
};

export type GetProjectListSharedResponse = GetProjectListSharedResponses[keyof GetProjectListSharedResponses];

export type GetProjectByIdUnityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/project/{id}/unity';
};

export type GetProjectByIdUnityErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetProjectByIdUnityError = GetProjectByIdUnityErrors[keyof GetProjectByIdUnityErrors];

export type GetProjectByIdUnityResponses = {
    /**
     * Default Response
     */
    200: {
        name: string;
        id: string;
        projectSasQueryParameters: string;
        description: string;
        maximumFlyingHeight: number;
        renderDistance: number;
        startingPoints: Array<{
            id: string;
            name: string;
            img: string;
            description: string;
            origin: {
                x: number;
                y: number;
                z: number;
            };
            target: {
                x: number;
                y: number;
                z: number;
            };
        }>;
        variants: Array<{
            id: string;
            name: string;
            baseLayers: Array<{
                url: string;
                id: string;
                name: string;
                type: 'TILES3D' | 'TERRAIN' | 'IMAGERY';
            }>;
            clippingPolygons: Array<{
                id: string;
                affectsTerrain: boolean;
                points: Array<{
                    x: number;
                    y: number;
                    z: number;
                }>;
            }>;
            models: Array<{
                id: string;
                attributes: {
                    [key: string]: string;
                };
                url: string;
                scale: {
                    x: number;
                    y: number;
                    z: number;
                };
                translation: {
                    x: number;
                    y: number;
                    z: number;
                };
                rotation: {
                    x: number;
                    y: number;
                    z: number;
                    w: number;
                };
            }>;
        }>;
    };
};

export type GetProjectByIdUnityResponse = GetProjectByIdUnityResponses[keyof GetProjectByIdUnityResponses];

export type GetPublicVisualAxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/visualAxes';
};

export type GetPublicVisualAxesErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetPublicVisualAxesError = GetPublicVisualAxesErrors[keyof GetPublicVisualAxesErrors];

export type GetPublicVisualAxesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        name: string;
        id: string;
        description: string;
        origin: {
            x: number;
            y: number;
            z: number;
        };
        target: {
            x: number;
            y: number;
            z: number;
        };
    }>;
};

export type GetPublicVisualAxesResponse = GetPublicVisualAxesResponses[keyof GetPublicVisualAxesResponses];

export type GetPublicBaseLayerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/baseLayer/list';
};

export type GetPublicBaseLayerListErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetPublicBaseLayerListError = GetPublicBaseLayerListErrors[keyof GetPublicBaseLayerListErrors];

export type GetPublicBaseLayerListResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        href: string;
        type: string;
        description: string;
    }>;
};

export type GetPublicBaseLayerListResponse = GetPublicBaseLayerListResponses[keyof GetPublicBaseLayerListResponses];

export type GetStatsGcData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/gc';
};

export type GetStatsGcErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetStatsGcError = GetStatsGcErrors[keyof GetStatsGcErrors];

export type GetStatsGcResponses = {
    /**
     * Default Response
     */
    200: boolean;
};

export type GetStatsGcResponse = GetStatsGcResponses[keyof GetStatsGcResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetStatsError = GetStatsErrors[keyof GetStatsErrors];

export type GetStatsResponses = {
    /**
     * Default Response
     */
    200: {
        memoryUsage: {
            rss: number;
            heapTotal: number;
            heapUsed: number;
            external: number;
            arrayBuffers: number;
        };
    };
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/info';
};

export type GetUserInfoErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * Default Response
     */
    200: {
        name: string;
        email: string;
        image: string | unknown;
    };
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type DeleteUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type DeleteUserErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Default Response
     */
    200: boolean;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type DeleteUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type DeleteUserByIdErrors = {
    /**
     * Bad request, input malformed.
     */
    400: Def0;
    /**
     * Unauthorized
     */
    401: Def1;
    /**
     * Forbidden
     */
    403: Def2;
    /**
     * Method not allowed
     */
    405: Def3;
    /**
     * Internal server error
     */
    500: Def4;
};

export type DeleteUserByIdError = DeleteUserByIdErrors[keyof DeleteUserByIdErrors];

export type DeleteUserByIdResponses = {
    /**
     * Default Response
     */
    200: boolean;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];
